FROM openjdk:8u191-jre-alpine3.8
WORKDIR /app
ENV TZ=America/Manaus
RUN apk add tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY d-scraper.war .
CMD echo "172.18.0.5      d-server-db" >> /etc/hosts \
    && echo "172.18.0.2      d-server-eureka" >> /etc/hosts \
    && java -jar d-scraper.war